// SDK features from SystemFeaturesMetadata in CP41.260814.003.B1.
// ArraySet indices are ordered by signed Java String.hashCode, not declaration order.
pub const SDK_FEATURES: [&str; 191] = [
    "android.hardware.sensor.proximity", // 0
    "android.software.dream_overlay", // 1
    "android.hardware.rotaryencoder.lowres", // 2
    "android.software.leanback_only", // 3
    "android.software.adoptable_storage", // 4
    "android.hardware.telephony.ims.singlereg", // 5
    "android.hardware.sensor.accelerometer", // 6
    "android.software.controls", // 7
    "android.hardware.faketouch", // 8
    "android.software.telecom", // 9
    "android.hardware.faketouch.multitouch.distinct", // 10
    "android.hardware.telephony.subscription", // 11
    "android.software.contextualsearch", // 12
    "android.hardware.telephony.euicc", // 13
    "android.hardware.reboot_escrow", // 14
    "android.hardware.broadcastradio", // 15
    "android.hardware.usb.accessory", // 16
    "android.hardware.hdmi.cec", // 17
    "android.hardware.telephony.cdma", // 18
    "android.hardware.telephony.data", // 19
    "android.hardware.telephony.mbms", // 20
    "android.software.aiseal", // 21
    "android.hardware.sensor.dynamic.head_tracker", // 22
    "android.software.erofs_legacy", // 23
    "android.software.backup", // 24
    "android.hardware.touchscreen", // 25
    "android.software.car.templates_host", // 26
    "android.hardware.touchscreen.multitouch", // 27
    "android.software.erofs", // 28
    "android.software.print", // 29
    "android.hardware.consumerir", // 30
    "android.hardware.ethernet", // 31
    "android.hardware.sensor.gyroscope_limited_axes_uncalibrated", // 32
    "android.software.activities_on_secondary_displays", // 33
    "android.hardware.wifi.rtt", // 34
    "android.hardware.sensor.heartrate", // 35
    "android.software.xr.api.spatial", // 36
    "android.software.device_lock", // 37
    "android.hardware.sensor.accelerometer_limited_axes", // 38
    "android.software.voice_recognizers", // 39
    "android.software.picture_in_picture", // 40
    "android.hardware.fingerprint", // 41
    "android.hardware.telephony.satellite", // 42
    "android.hardware.sensor.gyroscope", // 43
    "android.hardware.audio.low_latency", // 44
    "android.software.vulkan.deqp.level", // 45
    "android.software.cant_save_state", // 46
    "android.software.app_compat_overrides", // 47
    "android.hardware.security.model.compatible", // 48
    "android.hardware.telephony.messaging", // 49
    "android.hardware.telephony.calling", // 50
    "android.hardware.opengles.aep", // 51
    "android.hardware.type.television", // 52
    "android.hardware.tv.tuner", // 53
    "android.hardware.sensor.relative_humidity", // 54
    "android.hardware.type.pc", // 55
    "android.hardware.bluetooth", // 56
    "android.software.window_magnification", // 57
    "android.hardware.telephony.radio.access", // 58
    "android.hardware.type.embedded", // 59
    "android.hardware.camera.autofocus", // 60
    "android.hardware.telephony.gsm", // 61
    "android.hardware.telephony.ims", // 62
    "android.hardware.sensor.heartrate.ecg", // 63
    "android.software.incremental_delivery", // 64
    "android.software.sip.voip", // 65
    "android.hardware.se.omapi.ese", // 66
    "android.software.opengles.deqp.level", // 67
    "android.hardware.vr.high_performance", // 68
    "android.software.slices_disabled", // 69
    "android.hardware.bluetooth_le.channel_sounding", // 70
    "android.hardware.camera.concurrent", // 71
    "android.hardware.usb.host", // 72
    "android.hardware.usb.device", // 73
    "android.hardware.audio.output", // 74
    "android.software.ipsec_tunnel_migration", // 75
    "android.software.verified_boot", // 76
    "android.hardware.camera.flash", // 77
    "android.hardware.camera.front", // 78
    "android.hardware.sensor.hifi_sensors", // 79
    "android.hardware.gamepad", // 80
    "android.hardware.se.omapi.uicc", // 81
    "android.hardware.strongbox_keystore", // 82
    "android.hardware.audio.spatial.headtracking.low_latency", // 83
    "android.software.live_tv", // 84
    "android.hardware.screen.portrait", // 85
    "android.hardware.nfc", // 86
    "android.hardware.npu", // 87
    "android.hardware.uwb", // 88
    "android.hardware.sensor.ambient_temperature", // 89
    "android.hardware.vr.headtracking", // 90
    "android.hardware.sensor.stepdetector", // 91
    "android.hardware.keystore.single_use_key", // 92
    "android.software.home_screen", // 93
    "android.hardware.context_hub", // 94
    "android.hardware.type.xr_peripheral", // 95
    "android.hardware.microphone", // 96
    "android.hardware.xr.input.controller", // 97
    "android.software.expanded_picture_in_picture", // 98
    "android.hardware.sensor.heading", // 99
    "android.software.autofill", // 100
    "android.software.car.splitscreen_multitasking", // 101
    "android.software.securely_removes_users", // 102
    "android.software.vr.mode", // 103
    "android.software.leanback", // 104
    "android.hardware.bluetooth_le", // 105
    "android.hardware.sensor.compass", // 106
    "android.hardware.touchscreen.multitouch.jazzhand", // 107
    "android.hardware.sensor.barometer", // 108
    "android.software.app_widgets", // 109
    "android.software.sdksandbox.sdk_install_work_profile", // 110
    "android.hardware.telephony.carrierlock", // 111
    "android.software.input_methods", // 112
    "android.hardware.sensor.light", // 113
    "android.hardware.vulkan.version", // 114
    "android.software.companion_device_setup", // 115
    "android.software.device_admin", // 116
    "android.hardware.keystore.limited_use_key", // 117
    "android.hardware.wifi.passpoint", // 118
    "android.hardware.camera", // 119
    "android.hardware.type.watch", // 120
    "android.hardware.identity_credential_direct_access", // 121
    "android.software.credentials", // 122
    "android.hardware.device_unique_attestation", // 123
    "android.hardware.screen.landscape", // 124
    "android.software.device_id_attestation", // 125
    "android.hardware.felica", // 126
    "android.hardware.xr.input.eye_tracking", // 127
    "android.hardware.ram.normal", // 128
    "android.hardware.sensor.hinge_angle", // 129
    "android.hardware.type.automotive", // 130
    "android.hardware.se.omapi.sd", // 131
    "android.software.managed_users", // 132
    "android.hardware.lowpan", // 133
    "android.software.webview", // 134
    "android.hardware.sensor.stepcounter", // 135
    "android.hardware.camera.capability.manual_post_processing", // 136
    "android.hardware.ram.low", // 137
    "android.hardware.camera.any", // 138
    "android.software.car.display_compatibility", // 139
    "android.hardware.xr.input.hand_tracking", // 140
    "android.hardware.camera.capability.raw", // 141
    "android.hardware.vulkan.compute", // 142
    "android.software.connectionservice", // 143
    "android.hardware.touchscreen.multitouch.distinct", // 144
    "android.hardware.location.network", // 145
    "android.hardware.camera.ar", // 146
    "android.software.cts", // 147
    "android.software.sip", // 148
    "android.hardware.camera.capability.manual_sensor", // 149
    "android.software.app_enumeration", // 150
    "android.hardware.camera.level.full", // 151
    "android.software.game_service", // 152
    "android.hardware.identity_credential", // 153
    "android.software.car.templates_host.media", // 154
    "android.hardware.wifi.direct", // 155
    "android.software.live_wallpaper", // 156
    "android.software.ipsec_tunnels", // 157
    "android.hardware.sensor.gyroscope_limited_axes", // 158
    "android.hardware.thread_network", // 159
    "android.hardware.sensor.assist", // 160
    "android.software.freeform_window_management", // 161
    "android.software.communal_mode", // 162
    "android.hardware.audio.pro", // 163
    "android.hardware.nfc.hcef", // 164
    "android.hardware.nfc.uicc", // 165
    "android.hardware.location.gps", // 166
    "android.sofware.nfc.beam", // 167
    "android.software.midi", // 168
    "android.hardware.faketouch.multitouch.jazzhand", // 169
    "android.hardware.nfc.any", // 170
    "android.hardware.nfc.ese", // 171
    "android.hardware.nfc.hce", // 172
    "android.hardware.hardware_keystore", // 173
    "android.hardware.telephony.euicc.mep", // 174
    "android.hardware.wifi", // 175
    "android.hardware.location", // 176
    "android.hardware.vulkan.level", // 177
    "android.software.virtualization_framework", // 178
    "android.hardware.keystore.app_attest_key", // 179
    "android.hardware.sensor.accelerometer_limited_axes_uncalibrated", // 180
    "android.hardware.nfc.charging", // 181
    "android.hardware.camera.external", // 182
    "android.software.wallet_location_based_suggestions", // 183
    "android.hardware.wifi.aware", // 184
    "android.software.xr.api.openxr", // 185
    "android.software.secure_lock_screen", // 186
    "android.hardware.biometrics.face", // 187
    "android.hardware.biometrics.iris", // 188
    "android.hardware.telephony", // 189
    "android.software.file_based_encryption", // 190
];
